### ISSUE TITLE
运行mvn package，遇错

### ISSUE THREAD

**Issue by luckypoem** [abc123lzf/flyingsocks#4]
hi.

git clone https://github.com/abc123lzf/flyingsocks flyingsocks-by-abc123lzf
cd flyingsocks-by-abc123lzf
mvn package
显示：
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building flyingsocks-client 2.0
[INFO] ------------------------------------------------------------------------
Downloading: http://repo.maven.apache.org/maven2/com/lzf/flyingsocks-common/2.0/flyingsocks-common-2.0.pom
Downloading: http://repo.maven.apache.org/maven2/org/eclipse/swt/org.eclipse.swt.win32.win32.x86_64/4.3/org.eclipse.swt.win32.win32.x86_64-4.3.pom
Downloading: http://repo.maven.apache.org/maven2/org/jmock/jmock-junit4/2.12.0/jmock-junit4-2.12.0.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.154s
[INFO] Finished at: Wed Apr 01 16:23:51 CST 2020
[INFO] Final Memory: 8M/77M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project flyingsocks-client: Could not resolve dependencies for project com.lzf:flyingsocks-client:jar:2.0: Failed to collect dependencies at com.lzf:flyingsocks-common:jar:2.0: Failed to read artifact descriptor for com.lzf:flyingsocks-common:jar:2.0: Could not transfer artifact com.lzf:flyingsocks-common:pom:2.0 from/to central (http://repo.maven.apache.org/maven2): Failed to transfer file: http://repo.maven.apache.org/maven2/com/lzf/flyingsocks-common/2.0/flyingsocks-common-2.0.pom. Return code is: 501 , ReasonPhrase:HTTPS Required. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

怎么解决？

**Comment by DataFormate** [comment]
你先install flyingsockets-common这个包，然后再分别package client和serivce

**Comment by DataFormate** [comment]
> hi.
> 
> git clone https://github.com/abc123lzf/flyingsocks flyingsocks-by-abc123lzf
> cd flyingsocks-by-abc123lzf
> mvn package
> 显示：
> [INFO] Scanning for projects...
> [INFO]
> [INFO] ------------------------------------------------------------------------
> [INFO] Building flyingsocks-client 2.0
> [INFO] ------------------------------------------------------------------------
> Downloading: http://repo.maven.apache.org/maven2/com/lzf/flyingsocks-common/2.0/flyingsocks-common-2.0.pom
> Downloading: http://repo.maven.apache.org/maven2/org/eclipse/swt/org.eclipse.swt.win32.win32.x86_64/4.3/org.eclipse.swt.win32.win32.x86_64-4.3.pom
> Downloading: http://repo.maven.apache.org/maven2/org/jmock/jmock-junit4/2.12.0/jmock-junit4-2.12.0.pom
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 2.154s
> [INFO] Finished at: Wed Apr 01 16:23:51 CST 2020
> [INFO] Final Memory: 8M/77M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal on project flyingsocks-client: Could not resolve dependencies for project com.lzf:flyingsocks-client:jar:2.0: Failed to collect dependencies at com.lzf:flyingsocks-common:jar:2.0: Failed to read artifact descriptor for com.lzf:flyingsocks-common:jar:2.0: Could not transfer artifact com.lzf:flyingsocks-common:pom:2.0 from/to central (http://repo.maven.apache.org/maven2): Failed to transfer file: http://repo.maven.apache.org/maven2/com/lzf/flyingsocks-common/2.0/flyingsocks-common-2.0.pom. Return code is: 501 , ReasonPhrase:HTTPS Required. -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
> 
> 怎么解决？

你先install flyingsockets-common这个包，然后再分别package client和serivce

**Comment by abc123lzf** [comment]
参考v3.0分支的README

**Comment by briteming** [comment]
@DataFormate 
在服务器上，
git clone https://github.com/abc123lzf/flyingsocks
cd flyingsocks
cd common
mvn package
(没有遇错）

cd ..
cd server
mvn package
显示：
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------------< com.lzf:flyingsocks-server >---------------------
[INFO] Building flyingsocks-server 3.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/3.3.0/maven-assembly-plugin-3.3.0.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/3.3.0/maven-assembly-plugin-3.3.0.pom (16 kB at 23 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/34/maven-plugins-34.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/34/maven-plugins-34.pom (11 kB at 509 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/34/maven-parent-34.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/34/maven-parent-34.pom (43 kB at 1.2 MB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/apache/23/apache-23.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/apache/23/apache-23.pom (0 B at 0 B/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/3.3.0/maven-assembly-plugin-3.3.0.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-assembly-plugin/3.3.0/maven-assembly-plugin-3.3.0.jar (242 kB at 1.4 MB/s)
Downloading from maven-ali: https://maven.aliyun.com/nexus/content/repositories/central/com/lzf/flyingsocks-common/3.0-SNAPSHOT/maven-metadata.xml
Downloading from maven-ali: https://maven.aliyun.com/nexus/content/repositories/central/com/lzf/flyingsocks-common/3.0-SNAPSHOT/flyingsocks-common-3.0-SNAPSHOT.pom
[WARNING] The POM for com.lzf:flyingsocks-common:jar:3.0-SNAPSHOT is missing, no dependency information available
Downloading from maven-ali: https://maven.aliyun.com/nexus/content/repositories/central/org/xerial/sqlite-jdbc/3.34.0/sqlite-jdbc-3.34.0.pom
Downloaded from maven-ali: https://maven.aliyun.com/nexus/content/repositories/central/org/xerial/sqlite-jdbc/3.34.0/sqlite-jdbc-3.34.0.pom (6.5 kB at 5.6 kB/s)
Downloading from maven-ali: https://maven.aliyun.com/nexus/content/repositories/central/org/mybatis/mybatis/3.5.6/mybatis-3.5.6.pom
Downloaded from maven-ali: https://maven.aliyun.com/nexus/content/repositories/central/org/mybatis/mybatis/3.5.6/mybatis-3.5.6.pom (13 kB at 32 kB/s)
Downloading from maven-ali: https://maven.aliyun.com/nexus/content/repositories/central/org/mybatis/mybatis-parent/32/mybatis-parent-32.pom
Downloaded from maven-ali: https://maven.aliyun.com/nexus/content/repositories/central/org/mybatis/mybatis-parent/32/mybatis-parent-32.pom (48 kB at 53 kB/s)
Downloading from maven-ali: https://maven.aliyun.com/nexus/content/repositories/central/com/lzf/flyingsocks-common/3.0-SNAPSHOT/flyingsocks-common-3.0-SNAPSHOT.jar
Downloading from maven-ali: https://maven.aliyun.com/nexus/content/repositories/central/org/xerial/sqlite-jdbc/3.34.0/sqlite-jdbc-3.34.0.jar
Downloading from maven-ali: https://maven.aliyun.com/nexus/content/repositories/central/org/mybatis/mybatis/3.5.6/mybatis-3.5.6.jar
Downloaded from maven-ali: https://maven.aliyun.com/nexus/content/repositories/central/org/mybatis/mybatis/3.5.6/mybatis-3.5.6.jar (1.7 MB at 510 kB/s)
Downloaded from maven-ali: https://maven.aliyun.com/nexus/content/repositories/central/org/xerial/sqlite-jdbc/3.34.0/sqlite-jdbc-3.34.0.jar (7.3 MB at 1.3 MB/s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 14.791 s
[INFO] Finished at: 2021-03-25T03:24:18-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project flyingsocks-server: Could not resolve dependencies for project com.lzf:flyingsocks-server:jar:3.0-SNAPSHOT: Could not find artifact com.lzf:flyingsocks-common:jar:3.0-SNAPSHOT in maven-ali (https://maven.aliyun.com/nexus/content/repositories/central) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

怎么解决？

**Comment by abc123lzf** [comment]
@briteming 先执行mvn clean install -pl common

**Comment by briteming** [comment]
我在服务器上搞定了，但在mac上没搞定。可否上传mac上的客户端程序到https://github.com/abc123lzf/flyingsocks/releases？

**Comment by briteming** [comment]
hi.

我把服务器上生成的flyingsocks-client-3.0-SNAPSHOT-jar-with-dependencies.jar下载到mac电脑。

yudeMacBook-Air:~ brite$ java -XstartOnFirstThread -jar flyingsocks-client-3.0-SNAPSHOT-jar-with-dependencies.jar
<2021-03-26 11:18:50,743>[ INFO] flyingsocks client v3.0 start... - com.lzf.flyingsocks.client.ClientBoot
<2021-03-26 11:18:50,759>[ INFO] flyingsocks-client ready to initial. - LifecycleLogger
<2021-03-26 11:18:50,940>[ INFO] System Property set: apple.awt.UIElement=true - ConfigManager
<2021-03-26 11:18:51,095>[ WARN] Please use VM argument -XstartOnFirstThread on MacOS - SWTViewComponent
Exception in thread "main" java.lang.Error: java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	no swt-win32-4332 in java.library.path
	no swt-win32 in java.library.path
	Can't load library: /Users/brite/.swt/lib/macosx/x86_64/libswt-win32-4332.jnilib
	Can't load library: /Users/brite/.swt/lib/macosx/x86_64/libswt-win32.jnilib

	at com.lzf.flyingsocks.client.gui.swt.SWTViewComponent.<init>(SWTViewComponent.java:75)
	at com.lzf.flyingsocks.client.StandardClient.initInternal(StandardClient.java:71)
	at com.lzf.flyingsocks.LifecycleBase.init(LifecycleBase.java:54)
	at com.lzf.flyingsocks.client.ClientBoot.main(ClientBoot.java:52)
Caused by: java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	no swt-win32-4332 in java.library.path
	no swt-win32 in java.library.path
	Can't load library: /Users/brite/.swt/lib/macosx/x86_64/libswt-win32-4332.jnilib
	Can't load library: /Users/brite/.swt/lib/macosx/x86_64/libswt-win32.jnilib

	at org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
	at org.eclipse.swt.internal.Library.loadLibrary(Unknown Source)
	at org.eclipse.swt.internal.C.<clinit>(Unknown Source)
	at org.eclipse.swt.widgets.Display.<clinit>(Unknown Source)
	at com.lzf.flyingsocks.client.gui.swt.SWTViewComponent.<init>(SWTViewComponent.java:70)
	... 3 more
yudeMacBook-Air:~ brite$

如何解决？

**Comment by abc123lzf** [comment]
@briteming 客户端编译时使用指定了profile为macos没？

**Comment by briteming** [comment]
还是搞不定。
作者有空的话，还是上传mac上的客户端程序到https://github.com/abc123lzf/flyingsocks/releases吧。
谢谢你

**Comment by abc123lzf** [comment]
@briteming 已上传，亲测10.15.7下是可以运行的
