### ISSUE TITLE
怎么得到证书或私钥

### ISSUE THREAD

**Issue by hqgordon** [abc123lzf/flyingsocks#5]
在客户端与服务端的数据传输上，使用TLS 1.2加密。服务端需要持有证书和私钥文件（使用CA机构颁发的证书、私钥或者自签证书皆可）。

这句话的意思是只需要服务端有一个证书即可吗？这个证书该如何得到，有对应得到的教程吗？客户端不需要做对应的处理吗？

**Comment by abc123lzf** [comment]
@hqgordon 
CA证书可以通过阿里云免费申请，需要持有一个域名，申请完后就可以下载到公钥和私钥文件。
https://www.aliyun.com/product/cas

自签证书用openssl命令行工具就可以生成

建议使用CA证书
